---
week: 13주차
---

# 모던 자바스크립트 Deep Dive CH47. 에러 처리

## 에러 처리의 필요성

에러나 예외적인 상황에 대처하지 않고 방치하면 프로그램은 강제 종료된다. 에러나 예외적인 상황은 너무나 다양하기 때문에 프로그램이 강제 종료된다면 원인을 파악하여 대응하기 어렵다. 따라서 작성한 코드에서 언제나 에러나 예외적인 상황이 발생할 수 있다는 것을 전제하고 이에 대응하는 코드를 작성해야 한다.

### 에러 처리를 구현하는 방법

1. 예외적인 상황이 발생하면 반환하는 값을 if 문/단축 평가/옵셔널 체이닝 연산자를 통해 확인해서 처리하는 방법
2. 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법
   - ex. `try...catch...finally` 문

## try...catch...finally 문

`try...catch...finally` 문은 에러 처리 방법으로, `try...catch...finally` 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.

```js
try {
  // 실행할 코드 (에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생할 경우 실행되는 코드
  // err: try 코드 블록에서 발생한 Error 객체, catch 블록에서만 유효
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행
  // 불필요할 경우 생략 가능
}
```

## Error 객체

```js
const myError = new Error('Super Duper Dangerous Error');
```

* **Error 생성자 함수**
  - Error 객체 생성
  - 인수로 에러를 설명하는 에러 메시지 전달 가능

* **Error 객체**
  - message 프로퍼티: Error 생성자 함수에 인수로 전달한 에러 메시지
  - stack 프로퍼티: 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열, 디버깅 목적으로 사용

### Error 생성자 함수

자바스크립트는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다. 아래 생성자 함수가 생성한 에러 객체의 프로토타입은 모두 `Error.prototype`을 상속받는다.

| 생성자 함수    | 인스턴스                                                                       |
| -------------- | ------------------------------------------------------------------------------ |
| Error          | 일반적 에러 객체                                                               |
| SyntaxError    | 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체                |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체                         |
| TypeError      | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체         |
| RangeError     | 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체                            |
| URIError       | encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError      | eval 함수에서 발생하는 에러 객체                                               |

## throw 문

에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.

```js
throw 표현식;

try {
  // 표현식: 일반적으로 에러 객체 지정
  throw new Error('뭔가 이상이 있음');
} catch (err) { // err: throw 문으로 던진 에러 객체가 할당
  console.log(err);
}
```

## 에러의 전파

에러는 **호출자**<sup>caller</sup> 방향으로 전파된다. 즉, 콜 스택의 아래 방향으로 전파된다. 이때 throw된 에러를 캐치하여 적절히 대응한다면 프로그램을 강제 종료시키지 않고 코드의 실행 흐름을 복구할 수 있다.

그러나 비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없으므로 주의해야 한다.


